import { computed, ref, watch } from 'vue'

const supported_languages = ['zh', 'en']
const url_language = typeof window === 'undefined'
  ? ''
  : new URLSearchParams(window.location.search).get('lang')
const browser_language = typeof localStorage === 'undefined'
  ? ''
  : localStorage.getItem('fitness-language')
const initial_language = supported_languages.includes(url_language)
  ? url_language
  : browser_language
const language = ref(supported_languages.includes(initial_language) ? initial_language : 'zh')

const messages = {
  zh: {
    appName: '健身计划',
    navExercises: '动作库',
    navArticles: '科普文章',
    navFoods: '食物换算',
    navOnDemand: '自定训练',
    navTemplates: '训练模板',
    navPlan: '训练计划',
    navToday: '今日训练',
    todayEyebrow: '今日训练',
    todayTitle: '今天练什么',
    todaySubtitle: '按顺序完成动作处方，训练结束后记录本次打卡。',
    readyToTrain: '准备训练',
    completed: '已完成',
    workoutCompleted: '本次训练已完成',
    completeWorkout: '完成训练',
    completing: '提交中',
    restDay: '今天没有安排训练',
    restDayHint: '这是休息日，恢复也是计划的一部分。你可以查看完整计划了解下一次训练。',
    viewFullPlan: '查看完整计划',
    exercises: '个动作',
    navProfile: '用户档案',
    planEyebrow: '八周计划',
    planTitle: '我的训练计划',
    planSubtitle: '按周查看训练重点、动作处方和训练日期，点击动作可查看完整说明。',
    replaceWithTemplate: '用模板替换',
    selectTemplate: '选择模板',
    replaceWorkoutHint: '仅当前或未来未完成训练可替换。',
    replaceWorkoutConfirm: '确认用这个模板替换当前训练吗？',
    replaceWorkoutSuccess: '训练已替换为模板版本',
    noTemplatesAvailable: '还没有可用的训练模板',
    loadTemplatesFirst: '先到训练模板页保存一个模板，再回来替换训练。',
    activePlan: '执行中',
    planPeriod: '计划周期',
    week: '第',
    weeks: '周',
    workouts: '训练日',
    day: '第',
    scheduledDate: '训练日期',
    noActivePlan: '暂无执行中的训练计划',
    noActivePlanHint: '请先完善用户档案，再生成适合你的八周训练计划。',
    emptyPlan: '计划中暂时没有训练安排',
    goToProfile: '前往用户档案',
    focusPush: '推力训练',
    focusPull: '拉力训练',
    focusLegs: '腿部训练',
    focusFullBody: '全身训练',
    sets: '组数',
    reps: '次数',
    rpe: 'RPE',
    load: '负荷',
    feedback: '训练反馈',
    tooEasy: '太轻松',
    justRight: '刚刚好',
    tooHard: '太困难',
    hurt: '疼痛 / 不适',
    hurtBodyPart: '输入疼痛身体部位',
    submitFeedback: '提交反馈',
    feedbackSaved: '反馈已保存',
    exerciseSubstituted: '不安全动作已自动替换',
    exerciseRemovedForSafety: '没有安全替代动作，已从本次训练移除',
    profileEyebrow: '用户档案',
    profileTitle: '用户档案',
    profileSubtitle: '填写训练水平、目标、每周训练天数和可用器械，作为后续生成训练计划的输入。',
    fitnessLevel: '训练水平',
    goal: '训练目标',
    daysPerWeek: '每周训练天数',
    weightKg: '体重（kg）',
    weightKgHint: '可选，用于计算个性化饮食目标。',
    availableEquipment: '可用器械',
    saveProfile: '保存档案',
    saving: '保存中',
    profileSaved: '用户档案已保存',
    profileNotFound: '还没有用户档案，请填写后保存。',
    beginner: '新手',
    intermediate: '有经验',
    advanced: '进阶',
    fatLoss: '减脂',
    muscleGain: '增肌',
    endurance: '耐力',
    generalFitness: '综合健康',
    bodyWeight: '自重',
    dumbbell: '哑铃',
    barbell: '杠铃',
    kettlebell: '壶铃',
    band: '弹力带',
    cable: '绳索',
    exerciseEyebrow: '动作库',
    exerciseTitle: '动作库',
    searchPlaceholder: '搜索名称',
    emptyExercises: '暂无匹配的动作',
    view: '查看',
    back: '返回',
    cancel: '取消',
    backToPrevious: '返回上页',
    steps: '步骤',
    emptySteps: '暂无步骤说明',
    category: '分类',
    bodyPart: '身体部位',
    target: '目标肌群',
    equipment: '器械',
    muscleGroup: '协同肌群',
    secondary: '辅助肌群',
    exerciseFallback: '动作',
    knowledgeArticleEyebrow: '训练科普',
    knowledgeArticleTitle: '训练与营养知识',
    knowledgeArticleSubtitle: '用清晰、可靠的内容理解动作和训练方法。',
    knowledgeArticlePublished: '已发布文章',
    emptyArticles: '暂无已发布文章',
    relatedArticles: '相关科普文章',
    emptyRelatedArticles: '暂无相关文章',
    articleReferences: '文章引用动作',
    emptyArticleReferences: '本文暂未引用动作',
    exerciseReference: '动作',
    articleFoodReferences: '关联食物',
    articleFoodReference: '食物',
    foodEyebrow: '食物工具',
    foodTitle: '食物份量换算',
    foodSubtitle: '选择标准食物并输入份数，清楚查看对应宏量营养。仅作食物教育参考，不替代训练补给建议。',
    foodSearchPlaceholder: '搜索食物中英文名称',
    search: '搜索',
    emptyFoodItems: '暂无匹配的食物',
    foodStandardServing: '标准份量',
    foodConversionEyebrow: '可解释换算',
    foodConversionTitle: '按份量查看宏量',
    foodConversionHint: '结果以这项食物的标准份量为基础计算。',
    foodServings: '输入份数',
    foodServingsInvalid: '请输入大于 0 且不超过 100 的份数。',
    foodConvert: '换算营养',
    foodConversionResult: '换算结果',
    foodResultEmpty: '输入份数后即可查看换算结果',
    foodCategoryPROTEIN: '蛋白质',
    foodCategoryGRAIN: '主食',
    foodCategoryDAIRY: '乳制品',
    foodCategoryFRUIT: '水果',
    foodCategoryVEGETABLE: '蔬菜',
    foodCategoryOTHER: '其他',
    all: '全部',
    chest: '练胸',
    backTraining: '练背',
    shouldersTraining: '练肩',
    legsTraining: '练腿',
    coreTraining: '练核心',
    onDemandEyebrow: '按需训练',
    onDemandTitle: '自定今天的训练',
    onDemandSubtitle: '选择部位和本次可用器械，生成一套适合当前训练水平的动作处方。',
    trainingBodyPart: '训练部位',
    equipmentForThisWorkout: '本次可用器械',
    saveEquipmentToProfile: '同时保存到我的器械',
    generateWorkout: '生成训练',
    generatingWorkout: '生成中',
    generatedWorkout: '本次训练',
    replaceWorkout: '换一组',
    startWorkout: '开始训练',
    saveAsTemplate: '保存为模板',
    templateSaved: '已保存为模板，可后续复用或替换计划训练。',
    templateSavedShort: '已保存',
    customTemplateName: '自定训练',
    templateEyebrow: '训练模板',
    templateTitle: '我的训练模板',
    templateSubtitle: '管理从自定训练保存下来的模板。模板保留当时的处方，动作名称、媒体和教练提示使用最新内容。',
    createTemplateFromWorkout: '生成新的自定训练',
    emptyTemplates: '还没有保存的训练模板',
    templateActive: '可用',
    templateNeedsRepair: '需要修复',
    templateProfileChanged: '你的训练档案已变化；此模板仍保留保存时的处方。',
    templateName: '模板名称',
    templateNameRequired: '请输入模板名称。',
    editTemplate: '编辑模板',
    repairTemplate: '修复模板',
    saveTemplateChanges: '保存修改',
    templateUpdated: '训练模板已更新',
    templateStillNeedsRepair: '模板已保存，但仍需要修复处方。',
    templateConflict: '模板已被其他操作修改，已刷新最新版本，请重新编辑。',
    templateRepairHint: '该模板引用了停用动作或不兼容处方，请选择系统替代动作并调整处方后再使用。',
    templateRepairExerciseUnavailable: '该动作已停用，需要替换。',
    templateRepairEquipmentUnavailable: '当前档案器械不足，需要替换。',
    templateRepairPrescriptionIncompatible: '当前动作与保存的负荷类型不兼容，需要调整处方。',
    findSubstitutes: '查找替代动作',
    substituteExercise: '选择系统替代动作',
    templateNoSubstitutes: '当前器械条件下没有系统提供的替代动作。',
    deleteExercise: '删除动作',
    moveUp: '上移',
    moveDown: '下移',
    templateMinimumCount: '该部位至少需要 {count} 个动作。',
    loadType: '负荷类型',
    loadTypeAbsoluteWeight: '绝对重量',
    loadTypePercentOneRepMax: '1RM 百分比',
    loadTypeBodyweight: '自重',
    loadTypeRpeOnly: '仅 RPE',
    loadTypeDuration: '持续时间',
    deleteTemplate: '删除模板',
    deleteTemplateConfirm: '确认删除这个训练模板吗？删除后不能从模板列表恢复。',
    templateDeleted: '训练模板已删除',
    workoutDraft: '待开始',
    workoutInProgress: '进行中',
    coachCue: '教练提示',
    nutritionTips: '营养小贴士',
    nutritionTipsTitle: '给这次训练的补给建议',
    nutritionTipSnapshot: '体重快照',
    nutritionPreWorkout: '练前',
    nutritionPostWorkout: '练后',
    nutritionDaily: '全天',
    nutritionProtein: '蛋白质',
    nutritionCarbs: '碳水',
    nutritionFat: '脂肪',
    nutritionKcal: '热量',
    nutritionGrams: '克',
    nutritionKilocalories: '千卡',
    nutritionAbsolute: '固定值',
    nutritionPerKgBodyweight: '按体重',
  },
  en: {
    appName: 'Fitness App',
    navExercises: 'Exercises',
    navArticles: 'Articles',
    navFoods: 'Food Converter',
    navOnDemand: 'Custom Workout',
    navTemplates: 'Templates',
    navPlan: 'Plan',
    navToday: 'Today',
    todayEyebrow: 'Today Workout',
    todayTitle: 'What to Train Today',
    todaySubtitle: 'Follow each prescription in order, then check in when the workout is complete.',
    readyToTrain: 'Ready to Train',
    completed: 'Completed',
    workoutCompleted: 'Workout completed',
    completeWorkout: 'Complete Workout',
    completing: 'Completing',
    restDay: 'No workout scheduled today',
    restDayHint: 'Today is a recovery day. Rest is part of the plan; open the full schedule to see what is next.',
    viewFullPlan: 'View Full Plan',
    exercises: 'Exercises',
    navProfile: 'Profile',
    planEyebrow: '8-Week Plan',
    planTitle: 'My Training Plan',
    planSubtitle: 'Review weekly focus, exercise prescriptions, and scheduled dates. Open any exercise for full details.',
    replaceWithTemplate: 'Replace with Template',
    selectTemplate: 'Select Template',
    replaceWorkoutHint: 'Only current or future incomplete workouts can be replaced.',
    replaceWorkoutConfirm: 'Replace this workout with the selected template?',
    replaceWorkoutSuccess: 'Workout replaced with template version',
    noTemplatesAvailable: 'No usable workout templates yet',
    loadTemplatesFirst: 'Save a template first, then come back to replace a workout.',
    activePlan: 'Active',
    planPeriod: 'Plan Period',
    week: 'Week',
    weeks: 'Weeks',
    workouts: 'Workouts',
    day: 'Day',
    scheduledDate: 'Scheduled',
    noActivePlan: 'No active training plan',
    noActivePlanHint: 'Complete your profile first, then generate a personalized 8-week plan.',
    emptyPlan: 'This plan has no workouts yet',
    goToProfile: 'Go to Profile',
    focusPush: 'Push',
    focusPull: 'Pull',
    focusLegs: 'Legs',
    focusFullBody: 'Full Body',
    sets: 'Sets',
    reps: 'Reps',
    rpe: 'RPE',
    load: 'Load',
    feedback: 'Feedback',
    tooEasy: 'Too easy',
    justRight: 'Just right',
    tooHard: 'Too hard',
    hurt: 'Hurt / pain',
    hurtBodyPart: 'Enter painful body part',
    submitFeedback: 'Submit',
    feedbackSaved: 'Feedback saved',
    exerciseSubstituted: 'Unsafe exercise was replaced',
    exerciseRemovedForSafety: 'No safe substitute; exercise removed from this workout',
    profileEyebrow: 'UserProfile',
    profileTitle: 'User Profile',
    profileSubtitle: 'Set training level, goal, weekly training days, and available equipment for future Plan generation.',
    fitnessLevel: 'Fitness Level',
    goal: 'Goal',
    daysPerWeek: 'Days Per Week',
    weightKg: 'Weight (kg)',
    weightKgHint: 'Optional. Used to calculate personalized nutrition targets.',
    availableEquipment: 'Available Equipment',
    saveProfile: 'Save Profile',
    saving: 'Saving',
    profileSaved: 'Profile saved',
    profileNotFound: 'No profile yet. Fill the form and save it.',
    beginner: 'Beginner',
    intermediate: 'Intermediate',
    advanced: 'Advanced',
    fatLoss: 'Fat Loss',
    muscleGain: 'Muscle Gain',
    endurance: 'Endurance',
    generalFitness: 'General Fitness',
    bodyWeight: 'Body Weight',
    dumbbell: 'Dumbbell',
    barbell: 'Barbell',
    kettlebell: 'Kettlebell',
    band: 'Band',
    cable: 'Cable',
    exerciseEyebrow: 'Exercise',
    exerciseTitle: 'Exercises',
    searchPlaceholder: 'Search by name',
    emptyExercises: 'No matching exercises',
    view: 'View',
    back: 'Back',
    cancel: 'Cancel',
    backToPrevious: 'Back',
    steps: 'Steps',
    emptySteps: 'No instructions yet',
    category: 'Category',
    bodyPart: 'BodyPart',
    target: 'Target',
    equipment: 'Equipment',
    muscleGroup: 'Muscle Group',
    secondary: 'Secondary',
    exerciseFallback: 'Exercise',
    knowledgeArticleEyebrow: 'Training Knowledge',
    knowledgeArticleTitle: 'Training & Nutrition Knowledge',
    knowledgeArticleSubtitle: 'Clear, practical education for better movement and training decisions.',
    knowledgeArticlePublished: 'Published article',
    emptyArticles: 'No published articles yet',
    relatedArticles: 'Related articles',
    emptyRelatedArticles: 'No related articles yet',
    articleReferences: 'Exercises referenced in this article',
    emptyArticleReferences: 'This article does not reference any exercises yet',
    exerciseReference: 'Exercise',
    articleFoodReferences: 'Referenced foods',
    articleFoodReference: 'Food',
    foodEyebrow: 'Food Tool',
    foodTitle: 'Food Portion Converter',
    foodSubtitle: 'Choose a standard food and enter servings to see its macros clearly. This is educational and does not replace workout nutrition guidance.',
    foodSearchPlaceholder: 'Search food names in Chinese or English',
    search: 'Search',
    emptyFoodItems: 'No matching foods',
    foodStandardServing: 'Standard serving',
    foodConversionEyebrow: 'Explainable conversion',
    foodConversionTitle: 'See macros by portion',
    foodConversionHint: 'Results are calculated from this food item\'s standard serving.',
    foodServings: 'Servings',
    foodServingsInvalid: 'Enter a serving amount greater than 0 and no more than 100.',
    foodConvert: 'Convert nutrition',
    foodConversionResult: 'Conversion result',
    foodResultEmpty: 'Enter servings to view the conversion result',
    foodCategoryPROTEIN: 'Protein',
    foodCategoryGRAIN: 'Grain',
    foodCategoryDAIRY: 'Dairy',
    foodCategoryFRUIT: 'Fruit',
    foodCategoryVEGETABLE: 'Vegetable',
    foodCategoryOTHER: 'Other',
    all: 'All',
    chest: 'Chest',
    backTraining: 'Back',
    shouldersTraining: 'Shoulders',
    legsTraining: 'Legs',
    coreTraining: 'Core',
    onDemandEyebrow: 'On-Demand Workout',
    onDemandTitle: 'Build Today\'s Workout',
    onDemandSubtitle: 'Choose a body part and the equipment available now to generate a prescription for your current level.',
    trainingBodyPart: 'Body Part',
    equipmentForThisWorkout: 'Equipment Available Now',
    saveEquipmentToProfile: 'Also save to my equipment',
    generateWorkout: 'Generate Workout',
    generatingWorkout: 'Generating',
    generatedWorkout: 'Your Workout',
    replaceWorkout: 'Try Another',
    startWorkout: 'Start Workout',
    saveAsTemplate: 'Save as Template',
    templateSaved: 'Saved as a template for reuse or future plan replacement.',
    templateSavedShort: 'Saved',
    customTemplateName: 'Custom Workout',
    templateEyebrow: 'Workout Templates',
    templateTitle: 'My Workout Templates',
    templateSubtitle: 'Manage templates saved from custom workouts. Prescriptions stay snapshotted while exercise names, media, and coach cues stay live.',
    createTemplateFromWorkout: 'Generate New Custom Workout',
    emptyTemplates: 'No saved workout templates yet',
    templateActive: 'Active',
    templateNeedsRepair: 'Needs Repair',
    templateProfileChanged: 'Your profile has changed; this template keeps its saved prescription.',
    templateName: 'Template Name',
    templateNameRequired: 'Enter a template name.',
    editTemplate: 'Edit Template',
    repairTemplate: 'Repair Template',
    saveTemplateChanges: 'Save Changes',
    templateUpdated: 'Workout template updated',
    templateStillNeedsRepair: 'Template saved, but its prescription still needs repair.',
    templateConflict: 'This template changed elsewhere. The latest version is loaded; please edit again.',
    templateRepairHint: 'This template references an inactive exercise or an incompatible prescription. Choose a system substitute and adjust the prescription before using it.',
    templateRepairExerciseUnavailable: 'This exercise is inactive and needs a replacement.',
    templateRepairEquipmentUnavailable: 'Your current equipment is insufficient and needs a replacement.',
    templateRepairPrescriptionIncompatible: 'The saved load type is incompatible and needs a prescription adjustment.',
    findSubstitutes: 'Find Substitutes',
    substituteExercise: 'Choose a system substitute',
    templateNoSubstitutes: 'No system-provided substitute is available for the current equipment.',
    deleteExercise: 'Delete Exercise',
    moveUp: 'Move Up',
    moveDown: 'Move Down',
    templateMinimumCount: 'This body part needs at least {count} exercises.',
    loadType: 'Load Type',
    loadTypeAbsoluteWeight: 'Absolute Weight',
    loadTypePercentOneRepMax: 'Percent 1RM',
    loadTypeBodyweight: 'Bodyweight',
    loadTypeRpeOnly: 'RPE Only',
    loadTypeDuration: 'Duration',
    deleteTemplate: 'Delete Template',
    deleteTemplateConfirm: 'Delete this workout template? It cannot be restored from the template list.',
    templateDeleted: 'Workout template deleted',
    workoutDraft: 'Ready to Start',
    workoutInProgress: 'In Progress',
    coachCue: 'Coach Cue',
    nutritionTips: 'Nutrition Tips',
    nutritionTipsTitle: 'Fuel for this workout',
    nutritionTipSnapshot: 'weight snapshot',
    nutritionPreWorkout: 'Pre-workout',
    nutritionPostWorkout: 'Post-workout',
    nutritionDaily: 'Daily',
    nutritionProtein: 'Protein',
    nutritionCarbs: 'Carbs',
    nutritionFat: 'Fat',
    nutritionKcal: 'Calories',
    nutritionGrams: 'g',
    nutritionKilocalories: 'kcal',
    nutritionAbsolute: 'fixed target',
    nutritionPerKgBodyweight: 'per kg bodyweight',
  },
}

export function useLanguage() {
  const is_zh = computed(() => language.value === 'zh')

  function set_language(next_language) {
    if (supported_languages.includes(next_language)) {
      language.value = next_language
    }
  }

  function t(key) {
    return messages[language.value][key] || messages.en[key] || key
  }

  watch(language, (next_language) => {
    if (typeof localStorage !== 'undefined') {
      localStorage.setItem('fitness-language', next_language)
    }
  })

  return {
    is_zh,
    language,
    set_language,
    t,
  }
}
