import { computed, ref, watch } from 'vue'

const supported_languages = ['zh', 'en']
const url_language = typeof window === 'undefined'
  ? ''
  : new URLSearchParams(window.location.search).get('lang')
const browser_language = typeof localStorage === 'undefined'
  ? ''
  : localStorage.getItem('fitness-language')
const initial_language = supported_languages.includes(url_language)
  ? url_language
  : browser_language
const language = ref(supported_languages.includes(initial_language) ? initial_language : 'zh')

const messages = {
  zh: {
    appName: '健身计划',
    navExercises: '动作库',
    navPlan: '训练计划',
    navToday: '今日训练',
    todayEyebrow: '今日训练',
    todayTitle: '今天练什么',
    todaySubtitle: '按顺序完成动作处方，训练结束后记录本次打卡。',
    readyToTrain: '准备训练',
    completed: '已完成',
    workoutCompleted: '本次训练已完成',
    completeWorkout: '完成训练',
    completing: '提交中',
    restDay: '今天没有安排训练',
    restDayHint: '这是休息日，恢复也是计划的一部分。你可以查看完整计划了解下一次训练。',
    viewFullPlan: '查看完整计划',
    exercises: '个动作',
    navProfile: '用户档案',
    planEyebrow: '八周计划',
    planTitle: '我的训练计划',
    planSubtitle: '按周查看训练重点、动作处方和训练日期，点击动作可查看完整说明。',
    activePlan: '执行中',
    planPeriod: '计划周期',
    week: '第',
    weeks: '周',
    workouts: '训练日',
    day: '第',
    scheduledDate: '训练日期',
    noActivePlan: '暂无执行中的训练计划',
    noActivePlanHint: '请先完善用户档案，再生成适合你的八周训练计划。',
    emptyPlan: '计划中暂时没有训练安排',
    goToProfile: '前往用户档案',
    focusPush: '推力训练',
    focusPull: '拉力训练',
    focusLegs: '腿部训练',
    focusFullBody: '全身训练',
    sets: '组数',
    reps: '次数',
    rpe: 'RPE',
    load: '负荷',
    profileEyebrow: '用户档案',
    profileTitle: '用户档案',
    profileSubtitle: '填写训练水平、目标、每周训练天数和可用器械，作为后续生成训练计划的输入。',
    fitnessLevel: '训练水平',
    goal: '训练目标',
    daysPerWeek: '每周训练天数',
    availableEquipment: '可用器械',
    saveProfile: '保存档案',
    saving: '保存中',
    profileSaved: '用户档案已保存',
    profileNotFound: '还没有用户档案，请填写后保存。',
    beginner: '新手',
    intermediate: '有经验',
    advanced: '进阶',
    fatLoss: '减脂',
    muscleGain: '增肌',
    endurance: '耐力',
    generalFitness: '综合健康',
    bodyWeight: '自重',
    dumbbell: '哑铃',
    barbell: '杠铃',
    kettlebell: '壶铃',
    band: '弹力带',
    cable: '绳索',
    exerciseEyebrow: '动作库',
    exerciseTitle: '动作库',
    searchPlaceholder: '搜索名称',
    emptyExercises: '暂无匹配的动作',
    view: '查看',
    back: '返回',
    steps: '步骤',
    emptySteps: '暂无步骤说明',
    category: '分类',
    bodyPart: '身体部位',
    target: '目标肌群',
    equipment: '器械',
    muscleGroup: '协同肌群',
    secondary: '辅助肌群',
    exerciseFallback: '动作',
    all: '全部',
    chest: '练胸',
    backTraining: '练背',
    shouldersTraining: '练肩',
    legsTraining: '练腿',
    coreTraining: '练核心',
  },
  en: {
    appName: 'Fitness App',
    navExercises: 'Exercises',
    navPlan: 'Plan',
    navToday: 'Today',
    todayEyebrow: 'Today Workout',
    todayTitle: 'What to Train Today',
    todaySubtitle: 'Follow each prescription in order, then check in when the workout is complete.',
    readyToTrain: 'Ready to Train',
    completed: 'Completed',
    workoutCompleted: 'Workout completed',
    completeWorkout: 'Complete Workout',
    completing: 'Completing',
    restDay: 'No workout scheduled today',
    restDayHint: 'Today is a recovery day. Rest is part of the plan; open the full schedule to see what is next.',
    viewFullPlan: 'View Full Plan',
    exercises: 'Exercises',
    navProfile: 'Profile',
    planEyebrow: '8-Week Plan',
    planTitle: 'My Training Plan',
    planSubtitle: 'Review weekly focus, exercise prescriptions, and scheduled dates. Open any exercise for full details.',
    activePlan: 'Active',
    planPeriod: 'Plan Period',
    week: 'Week',
    weeks: 'Weeks',
    workouts: 'Workouts',
    day: 'Day',
    scheduledDate: 'Scheduled',
    noActivePlan: 'No active training plan',
    noActivePlanHint: 'Complete your profile first, then generate a personalized 8-week plan.',
    emptyPlan: 'This plan has no workouts yet',
    goToProfile: 'Go to Profile',
    focusPush: 'Push',
    focusPull: 'Pull',
    focusLegs: 'Legs',
    focusFullBody: 'Full Body',
    sets: 'Sets',
    reps: 'Reps',
    rpe: 'RPE',
    load: 'Load',
    profileEyebrow: 'UserProfile',
    profileTitle: 'User Profile',
    profileSubtitle: 'Set training level, goal, weekly training days, and available equipment for future Plan generation.',
    fitnessLevel: 'Fitness Level',
    goal: 'Goal',
    daysPerWeek: 'Days Per Week',
    availableEquipment: 'Available Equipment',
    saveProfile: 'Save Profile',
    saving: 'Saving',
    profileSaved: 'Profile saved',
    profileNotFound: 'No profile yet. Fill the form and save it.',
    beginner: 'Beginner',
    intermediate: 'Intermediate',
    advanced: 'Advanced',
    fatLoss: 'Fat Loss',
    muscleGain: 'Muscle Gain',
    endurance: 'Endurance',
    generalFitness: 'General Fitness',
    bodyWeight: 'Body Weight',
    dumbbell: 'Dumbbell',
    barbell: 'Barbell',
    kettlebell: 'Kettlebell',
    band: 'Band',
    cable: 'Cable',
    exerciseEyebrow: 'Exercise',
    exerciseTitle: 'Exercises',
    searchPlaceholder: 'Search by name',
    emptyExercises: 'No matching exercises',
    view: 'View',
    back: 'Back',
    steps: 'Steps',
    emptySteps: 'No instructions yet',
    category: 'Category',
    bodyPart: 'BodyPart',
    target: 'Target',
    equipment: 'Equipment',
    muscleGroup: 'Muscle Group',
    secondary: 'Secondary',
    exerciseFallback: 'Exercise',
    all: 'All',
    chest: 'Chest',
    backTraining: 'Back',
    shouldersTraining: 'Shoulders',
    legsTraining: 'Legs',
    coreTraining: 'Core',
  },
}

export function useLanguage() {
  const is_zh = computed(() => language.value === 'zh')

  function set_language(next_language) {
    if (supported_languages.includes(next_language)) {
      language.value = next_language
    }
  }

  function t(key) {
    return messages[language.value][key] || messages.en[key] || key
  }

  watch(language, (next_language) => {
    if (typeof localStorage !== 'undefined') {
      localStorage.setItem('fitness-language', next_language)
    }
  })

  return {
    is_zh,
    language,
    set_language,
    t,
  }
}
