bind 0.0.0.0
protected-mode yes
port 6379

dir /data
appendonly yes
appendfsync everysec

save 900 1
save 300 10
save 60 10000

aclfile /data/users.acl
databases 16
tcp-keepalive 300
timeout 0

maxmemory 512mb
maxmemory-policy allkeys-lru

loglevel notice
